# Generated by Django 5.1 on 2024-09-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_renter_agreement_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
