# Generated by Django 5.1 on 2024-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='pay_for',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
