# Generated by Django 5.1 on 2024-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rent_pay_for_alter_rent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='pay_for',
            field=models.DateField(),
        ),
    ]
